language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"
script:
- "./gradlew build connectedCheck"
before_install:
- openssl aes-256-cbc -K $encrypted_dcc914e7eb3f_key -iv $encrypted_dcc914e7eb3f_iv
  -in app/src/release/google-services.json.enc -out app/src/release/google-services.json -d
